# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('create_date', models.DateTimeField(verbose_name='Data publikacji')),
                ('notice_poster', models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('notice_image1', models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('notice_image2', models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('notice_image3', models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('notice_image4', models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Ogłoszenia',
                'verbose_name': 'Ogłoszenie',
            },
        ),
    ]
