# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_poster',
            field=models.FileField(upload_to='Notice/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia głównego'),
        ),
    ]
